Repository elebumm/RedditVideoMakerBot, pull requests merged in 2022-06, with the labels that each got.

#205 Added TTS reading the text of the post if present
  .env.template
  main.py
  reddit/subreddit.py
  video_creation/final_video.py
  video_creation/voices.py
Labels: enhancement, tts

#336 Grammar-ized contributing.md
  CONTRIBUTING.md
Labels: documentation

#341 Add GPLv3
  LICENSE
Labels: before next release

#349 Move legacy branch into develop
  README.md
Labels: documentation

#345 setup.py refactored, added shebang lines and formatted files with python-black
  CONTRIBUTING.md
  build.sh
  main.py
  reddit/subreddit.py
  run.sh
  setup.py
  utils/console.py
  utils/loader.py
  video_creation/background.py
  video_creation/final_video.py
  video_creation/screenshot_downloader.py
  video_creation/voices.py
Labels: enhancement, after next release

#311 tts will no longer read aloud link
  video_creation/voices.py
Labels: tts, bug fix

#368 Removed "Click to see nsfw" Button in Screenshot
  video_creation/screenshot_downloader.py
Labels: bug fix

#261 Option to filter the comments by length (min and max number of characters)
  .env.template
  reddit/subreddit.py
Labels: enhancement

#354 UX changes / Gives User More Info
  main.py
  reddit/subreddit.py
  video_creation/final_video.py
  video_creation/screenshot_downloader.py
  video_creation/voices.py
Labels: enhancement, merge conflicts
