Repository elebumm/RedditVideoMakerBot, pull requests merged in 2022-12, with the labels that each got.

#1314 Added new gameplay video options
  utils/.config.template.toml
  utils/backgrounds.json
Labels: keep

#1288 Added the story mode with 2 methods and add min comment lenght
  TTS/TikTok.py
  TTS/aws_polly.py
  TTS/engine_wrapper.py
  TTS/pyttsx.py
  TTS/streamlabs_polly.py
  fonts/LICENSE.txt
  fonts/Roboto-Black.ttf
  fonts/Roboto-Bold.ttf
  fonts/Roboto-Medium.ttf
  fonts/Roboto-Regular.ttf
  main.py
  reddit/subreddit.py
  requirements.txt
  utils/.config.template.toml
  utils/console.py
  utils/imagenarator.py
  utils/posttextparser.py
  utils/settings.py
  utils/subreddit.py
  utils/version.py
  utils/video.py
  utils/videos.py
  utils/voice.py
  video_creation/background.py
  video_creation/final_video.py
  video_creation/screenshot_downloader.py
  video_creation/voices.py
Labels: enhancement, keep

#1391 Add ai methods that sort threads based on content similarity w/ given…
  reddit/subreddit.py
  requirements.txt
  utils/.config.template.toml
  utils/ai_methods.py
  utils/subreddit.py
Labels: enhancement

#1277 Custom resolution
  TTS/GTTS.py
  TTS/aws_polly.py
  TTS/engine_wrapper.py
  utils/.config.template.toml
  utils/console.py
  utils/settings.py
  video_creation/final_video.py
  video_creation/screenshot_downloader.py
  video_creation/voices.py
Labels: keep
