Repository elebumm/RedditVideoMakerBot, pull requests merged in 2023-05, with the labels that each got.

#1578 Adds zoom function
  TTS/engine_wrapper.py
  utils/.config.template.toml
  video_creation/final_video.py
  video_creation/screenshot_downloader.py
Labels: before next release, keep

#1619 Adds elevenlabs TTS
  TTS/elevenlabs.py
  main.py
  requirements.txt
  utils/.config.template.toml
  video_creation/voices.py
Labels: before next release

#1626 Fixed Opacity Function
  video_creation/final_video.py
Labels: bug fix, before next release, keep

#1664 fixes title query
  video_creation/screenshot_downloader.py
Labels: bug fix, after next release

#1607 Version 3.2
  .github/workflows/codesee-arch-diagram.yml
  .gitignore
  Dockerfile
  GUI/layout.html
  README.md
  TTS/elevenlabs.py
  TTS/engine_wrapper.py
  main.py
  reddit/subreddit.py
  requirements.txt
  run.bat
  utils/.config.template.toml
  utils/background_audios.json
  utils/background_videos.json
  utils/cleanup.py
  utils/ffmpeg_install.py
  utils/imagenarator.py
  utils/playwright.py
  utils/posttextparser.py
  utils/subreddit.py
  video_creation/background.py
  video_creation/final_video.py
  video_creation/screenshot_downloader.py
  video_creation/voices.py
Labels: keep
